[package]
name = "rust-game"
version = "0.1.0"
authors = ["Tailcalled <tailcalled@gmail.com>", "Alice Ryhl <alice@ryhl.io>"]
edition = "2018"

[dependencies]
termion = "1.5"
serde = "1.0"
bincode = "1.2"
crossbeam = "0.7"
get_if_addrs = "0.5"
